{% set version = "2.12" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-buildmer
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/buildmer_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/buildmer/buildmer_{{ version }}.tar.gz
  sha256: 43aa08a3c466dbe812fdbdccdfc702fc9e8acbd7a7d8bcf7243af1556b248d09

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-lme4
    - r-mgcv
    - r-nlme
    - r-reformulas
  run:
    - r-base
    - r-lme4
    - r-mgcv
    - r-nlme
    - r-reformulas

test:
  commands:
    - $R -e "library('buildmer')"           # [not win]
    - "\"%R%\" -e \"library('buildmer')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=buildmer
  license: BSD-2-Clause
  summary: Finds the largest possible regression model that will still converge for various types of regression analyses (including mixed models and generalized additive models) and then optionally performs stepwise elimination similar to the forward and backward effect-selection methods in SAS, based on the change in log-likelihood
    or its significance, Akaike's Information Criterion, the Bayesian Information Criterion, the explained deviance, or the F-test of the change in R².
  license_family: BSD
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/BSD_2_clause'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester

# The original CRAN metadata for this package was:
# Package: buildmer
# Title: Stepwise Elimination and Term Reordering for Mixed-Effects Regression
# Version: 2.8
# Authors@R: person(c("Cesko", "C."), "Voeten", email = "cvoeten@gmail.com", role = c("aut", "cre"), comment = c(ORCID="0000-0003-4687-9973"))
# Description: Finds the largest possible regression model that will still converge for various types of regression analyses (including mixed models and generalized additive models) and then optionally performs stepwise elimination similar to the forward and backward effect-selection methods in SAS, based on the change in log-likelihood or its significance, Akaike's Information Criterion, the Bayesian Information Criterion, the explained deviance, or the F-test of the change in R2.
# Depends: R (>= 3.2)
# Imports: graphics, lme4, methods, mgcv, nlme, stats, utils
# Suggests: GLMMadaptive, MASS, gamm4, glmertree, glmmTMB, knitr, lmerTest, nnet, ordinal, parallel, partykit, pbkrtest, rmarkdown, testthat
# License: FreeBSD
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 7.2.1
# BugReports: https://github.com/cvoeten/buildmer/issues
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2023-01-06 15:23:52 UTC; cesko
# Author: Cesko C. Voeten [aut, cre] (<https://orcid.org/0000-0003-4687-9973>)
# Maintainer: Cesko C. Voeten <cvoeten@gmail.com>
# Repository: CRAN
# Date/Publication: 2023-01-06 19:20:02 UTC
# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
